if (!require("tidyverse")) install.packages("tidyverse")
if (!require("shiny")) install.packages("shiny")
if (!require("ggplot2")) install.packages("ggplot2")
if (!require("heatmaply")) install.packages("heatmaply")
if (!require("plotly")) install.packages("plotly")
if (!require("shinyjs")) install.packages("shinyjs")
if (!require("shinyWidgets")) install.packages("shinyWidgets")
if (!require("leaflet")) install.packages("leaflet")
if (!require("gganimate")) install.packages("gganimate")
if (!require("gifski")) install.packages("gifski")

library(tidyverse)
complaints <- read_csv("Complaints_Data_Wrangled.csv")
complaints$RPT_DT <- as.Date(complaints$RPT_DT, format = "%m/%d/%Y")
